### ISSUE TITLE
Provide a configuration example

### ISSUE THREAD

**Issue by ccamara** [greenape/mktheapidocs#43]
Here I am, using yet another of your mkdocs plugins and asking again for help (sorry, I am pretty new to python).

I have read the readme file, but haven't found enough guidance on what to write in the `mkdocs.yml` (I am not yet familiar with python's naming -modules and so on- and I am struggling with that)

Provided the following structure:

```
├── docs
├── mkdocs.yml
├── osmi_helpers
│   ├── data_gathering.py
│   ├── __init__.py
│   └── __pycache__
└── README.md
```
I wrote the following in `mkdocs.yml`:

```
plugins:
  - mktheapidocs:
      modules:
        osmi_helpers.data_gathering:
          section:custom
          source_repo:osmi_helpers/data_gathering.py
```
but when running `mkdocs serve` I get the following error:

```
$ mkdocs serve
INFO    -  Building documentation... 
Traceback (most recent call last):
  File "/home/ccamara/anaconda3/envs/osm_imports_preparations/bin/mkdocs", line 10, in <module>
    sys.exit(cli())
  File "/home/ccamara/anaconda3/envs/osm_imports_preparations/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ccamara/anaconda3/envs/osm_imports_preparations/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ccamara/anaconda3/envs/osm_imports_preparations/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ccamara/anaconda3/envs/osm_imports_preparations/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ccamara/anaconda3/envs/osm_imports_preparations/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ccamara/anaconda3/envs/osm_imports_preparations/lib/python3.7/site-packages/mkdocs/__main__.py", line 143, in serve_command
    **kwargs
  File "/home/ccamara/anaconda3/envs/osm_imports_preparations/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 141, in serve
    config = builder()
  File "/home/ccamara/anaconda3/envs/osm_imports_preparations/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 136, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/ccamara/anaconda3/envs/osm_imports_preparations/lib/python3.7/site-packages/mkdocs/commands/build.py", line 239, in build
    config = config['plugins'].run_event('config', config)
  File "/home/ccamara/anaconda3/envs/osm_imports_preparations/lib/python3.7/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/home/ccamara/anaconda3/envs/osm_imports_preparations/lib/python3.7/site-packages/mktheapidocs/plugin.py", line 74, in on_config
    target = details["section"]
TypeError: string indices must be integers

```
(see commit : https://github.com/mapcolabora/osm_imports_preparations/commit/e9715443171abb5ec190dd73133c7d200a1f3ec9 )

What am I doing wrong?

**Comment by greenape** [comment]
Think it'll be the lack of a space after the `:`, try:

```yaml
plugins:
  - mktheapidocs:
      modules:
        osmi_helpers.data_gathering:
          section: custom
          source_repo: osmi_helpers/data_gathering.py
```

**Comment by ccamara** [comment]
Same on me! you're right! Now `mkdoc serve` does not prompt any error but the following warning, and does not generate any extra `.md` file with the docstring as I expected:

```
INFO    -  Building documentation... 
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - custom/osmi_helpers/__init__.py
  - custom/osmi_helpers/data_gathering.py 
WARNING -  Documentation file 'custom/osmi_helpers/data_gathering.py' contains a link to 'custom/osmi_helpers/osmi_helpers/data_gathering.py/osmi_helpers/data_gathering.py' which is not found in the documentation files. 
```

I believe the problem is that I have not understood what the fields `section` and `source_repo` mean  (I thought section would be the folder where the md files would be created, under `docs` folder) and/or what I should expect from the plugin.

Could you please provide some (more) guidance?

**Comment by yesi-sg** [comment]
I have a similar question about `yml` configuration. Is the plugin syntax enough to docs page? 

What is the setup to display `.py` modules in navigation? Readme says to add a placeholder, but there are no examples. 

Can you please share some examples of yml, nav and how it renders with mkdocs?

**Comment by hcoohb** [comment]
I am too a bit confused on what the parameters mean and how to use this plugin.
It would be great if the doc could clarify those points with maybe an example?

Thanks a lot for this project.

**Comment by 852023301** [comment]
I encountered this problem because the theme was not installed。

my mkdocs.yml:

`
theme: material
`
When I use `pip install mkdocs-material`,everything is ok.
